FROM ubuntu:16.04

RUN apt-get update && apt-get install -y openalpr openalpr-daemon openalpr-utils libopenalpr-dev python3 python3-pip

WORKDIR /app

COPY ./app /app

RUN python3 -m pip install pip==20.3.4
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["gunicorn", "--workers", "3", "-b", "0.0.0.0:8000", "app:app"]