services:
  plate-recognition-ws:
    build:
      context: ./plate-recognition-ws
      dockerfile: Dockerfile
    image: plate-recognition-ws
    container_name: plate-recognition-ws
    ports:
      - '6000:5000'
    volumes:
      - ./plate-recognition-ws/app:/app
    environment:
      - ENV=development
    restart: always

  # blob storage
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ main port
      - '15672:15672' # RabbitMQ management plugin
    environment:
      RABBITMQ_DEFAULT_USER: user # Default username
      RABBITMQ_DEFAULT_PASS: password # Default password
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27018:27017'
    volumes:
      - ./mongo_data:/data/db

  app-server:
    build:
      context: ./app-server
      dockerfile: Dockerfile
    image: app-server
    container_name: app-server
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      JWT_SECRET: c6bc685865d8c732a5aa521d21728e3e6f17e36754cc997d7e8e170667259d2bf743cd095060d7a4bebe12ed1382d6f86cfb8ab5183a217447a7cbf49a685734
      PLATE_RECOGNITION_WS_URL: http://plate-recognition-ws:5000
      MESSAGE_BROKER_URL: amqp://user:password@rabbitmq:5672
      DATABASE_URL: mongodb://mongodb:27017
      DATABASE_NAME: bumbereye
      ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC: 3600
      IMAGE_SAVE_ENABLED: true
    restart: always
    depends_on:
      - rabbitmq
      - mongodb

  image-ws:
    build:
      context: ./image-ws
      dockerfile: Dockerfile
    image: image-ws
    container_name: image-ws
    environment:
      MINIO_ENDPOINT: minio # The MinIO server address (or IP)
      MINIO_PORT: 9000 # The MinIO server port
      MINIO_ACCESS_KEY: minioadmin # MinIO Access Key
      MINIO_SECRET_KEY: minioadmin # MinIO Secret Key
      MINIO_BUCKET: bumbereye # Your MinIO bucket name
      MINIO_USE_SSL: false
      MESSAGE_BROKER_URL: amqp://user:password@rabbitmq:5672
    restart: always
    depends_on:
      - minio
      - rabbitmq
